os:
    - linux

language: java

env:
    - GRAALVM_VERSION="1.0.0-rc12"

install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="macos"; fi
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
        curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-$DOWNLOAD_OS_NAME-amd64.tar.gz" --output graalvm.tar.gz
        tar -xzf graalvm.tar.gz
        export JAVA_HOME="$(pwd)/graalvm-ce-$GRAALVM_VERSION"
        if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi

script:
    - mvn clean
    - mvn package
    - ./prettymd test.md | tee out1.txt
    - $JAVA_HOME/bin/java -cp target/prettymd.jar com.pascal.prettymd.FormatPretty test.md | tee out2.txt
    - diff out1.txt out2.txt
    - ./prettymd test.md example.js | tee out1.txt
    - $JAVA_HOME/bin/java -cp target/prettymd.jar com.pascal.prettymd.FormatPretty test.md example.js | tee out2.txt
    - diff out1.txt out2.txt
